create table events ( id serial NOT NULL,
			name varchar(255) NULL,
			start_date timestamp NULL,
			end_date timestamp NULL,
			contact_email varchar(255) NULL,
			contact_name varchar(100) NULL,
			contact_number char(15) NULL,
			category varchar (100) NULL,
			event_type varchar(20) NULL,
			event_link varchar(2084) NULL,
			details_link varchar(2084) NULL,
			location varchar(255) NULL,
			description VARCHAR(60000) NULL,
			primary key (id));
